// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/agent/registry/v1/agent_registry.proto

package agentregistryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentRegistry_BootstrapEnrollAgent_FullMethodName = "/agent.registry.v1.AgentRegistry/BootstrapEnrollAgent"
	AgentRegistry_AgentControlStream_FullMethodName   = "/agent.registry.v1.AgentRegistry/AgentControlStream"
)

// AgentRegistryClient is the client API for AgentRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentRegistryClient interface {
	BootstrapEnrollAgent(ctx context.Context, in *BootstrapEnrollAgentRequest, opts ...grpc.CallOption) (*BootstrapEnrollAgentResponse, error)
	AgentControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToHypervisor, HypervisorToAgent], error)
}

type agentRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRegistryClient(cc grpc.ClientConnInterface) AgentRegistryClient {
	return &agentRegistryClient{cc}
}

func (c *agentRegistryClient) BootstrapEnrollAgent(ctx context.Context, in *BootstrapEnrollAgentRequest, opts ...grpc.CallOption) (*BootstrapEnrollAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootstrapEnrollAgentResponse)
	err := c.cc.Invoke(ctx, AgentRegistry_BootstrapEnrollAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRegistryClient) AgentControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToHypervisor, HypervisorToAgent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentRegistry_ServiceDesc.Streams[0], AgentRegistry_AgentControlStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentToHypervisor, HypervisorToAgent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRegistry_AgentControlStreamClient = grpc.BidiStreamingClient[AgentToHypervisor, HypervisorToAgent]

// AgentRegistryServer is the server API for AgentRegistry service.
// All implementations must embed UnimplementedAgentRegistryServer
// for forward compatibility.
type AgentRegistryServer interface {
	BootstrapEnrollAgent(context.Context, *BootstrapEnrollAgentRequest) (*BootstrapEnrollAgentResponse, error)
	AgentControlStream(grpc.BidiStreamingServer[AgentToHypervisor, HypervisorToAgent]) error
	mustEmbedUnimplementedAgentRegistryServer()
}

// UnimplementedAgentRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentRegistryServer struct{}

func (UnimplementedAgentRegistryServer) BootstrapEnrollAgent(context.Context, *BootstrapEnrollAgentRequest) (*BootstrapEnrollAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BootstrapEnrollAgent not implemented")
}
func (UnimplementedAgentRegistryServer) AgentControlStream(grpc.BidiStreamingServer[AgentToHypervisor, HypervisorToAgent]) error {
	return status.Errorf(codes.Unimplemented, "method AgentControlStream not implemented")
}
func (UnimplementedAgentRegistryServer) mustEmbedUnimplementedAgentRegistryServer() {}
func (UnimplementedAgentRegistryServer) testEmbeddedByValue()                       {}

// UnsafeAgentRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRegistryServer will
// result in compilation errors.
type UnsafeAgentRegistryServer interface {
	mustEmbedUnimplementedAgentRegistryServer()
}

func RegisterAgentRegistryServer(s grpc.ServiceRegistrar, srv AgentRegistryServer) {
	// If the following call pancis, it indicates UnimplementedAgentRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentRegistry_ServiceDesc, srv)
}

func _AgentRegistry_BootstrapEnrollAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapEnrollAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRegistryServer).BootstrapEnrollAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRegistry_BootstrapEnrollAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRegistryServer).BootstrapEnrollAgent(ctx, req.(*BootstrapEnrollAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRegistry_AgentControlStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentRegistryServer).AgentControlStream(&grpc.GenericServerStream[AgentToHypervisor, HypervisorToAgent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRegistry_AgentControlStreamServer = grpc.BidiStreamingServer[AgentToHypervisor, HypervisorToAgent]

// AgentRegistry_ServiceDesc is the grpc.ServiceDesc for AgentRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.registry.v1.AgentRegistry",
	HandlerType: (*AgentRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BootstrapEnrollAgent",
			Handler:    _AgentRegistry_BootstrapEnrollAgent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AgentControlStream",
			Handler:       _AgentRegistry_AgentControlStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent/registry/v1/agent_registry.proto",
}
