// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/agent/registry/v1/agent_enrollment.proto

package agentregistryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BootstrapEnrollAgentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BootstrapToken   string                 `protobuf:"bytes,1,opt,name=bootstrap_token,json=bootstrapToken,proto3" json:"bootstrap_token,omitempty"`
	RequestedAgentId string                 `protobuf:"bytes,2,opt,name=requested_agent_id,json=requestedAgentId,proto3" json:"requested_agent_id,omitempty"`
	CsrPem           string                 `protobuf:"bytes,3,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	Hostname         string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BootstrapEnrollAgentRequest) Reset() {
	*x = BootstrapEnrollAgentRequest{}
	mi := &file_proto_agent_registry_v1_agent_enrollment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapEnrollAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapEnrollAgentRequest) ProtoMessage() {}

func (x *BootstrapEnrollAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_registry_v1_agent_enrollment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapEnrollAgentRequest.ProtoReflect.Descriptor instead.
func (*BootstrapEnrollAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_registry_v1_agent_enrollment_proto_rawDescGZIP(), []int{0}
}

func (x *BootstrapEnrollAgentRequest) GetBootstrapToken() string {
	if x != nil {
		return x.BootstrapToken
	}
	return ""
}

func (x *BootstrapEnrollAgentRequest) GetRequestedAgentId() string {
	if x != nil {
		return x.RequestedAgentId
	}
	return ""
}

func (x *BootstrapEnrollAgentRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *BootstrapEnrollAgentRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type BootstrapEnrollAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ClientCertPem string                 `protobuf:"bytes,2,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	CaCertPem     string                 `protobuf:"bytes,3,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	CertNotAfter  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=cert_not_after,json=certNotAfter,proto3" json:"cert_not_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapEnrollAgentResponse) Reset() {
	*x = BootstrapEnrollAgentResponse{}
	mi := &file_proto_agent_registry_v1_agent_enrollment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapEnrollAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapEnrollAgentResponse) ProtoMessage() {}

func (x *BootstrapEnrollAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_registry_v1_agent_enrollment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapEnrollAgentResponse.ProtoReflect.Descriptor instead.
func (*BootstrapEnrollAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_registry_v1_agent_enrollment_proto_rawDescGZIP(), []int{1}
}

func (x *BootstrapEnrollAgentResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BootstrapEnrollAgentResponse) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

func (x *BootstrapEnrollAgentResponse) GetCaCertPem() string {
	if x != nil {
		return x.CaCertPem
	}
	return ""
}

func (x *BootstrapEnrollAgentResponse) GetCertNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CertNotAfter
	}
	return nil
}

type RegisterHost struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AgentId          string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId           string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Hostname         string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PrivateIp        string                 `protobuf:"bytes,4,opt,name=private_ip,json=privateIp,proto3" json:"private_ip,omitempty"`
	HypervisorType   string                 `protobuf:"bytes,5,opt,name=hypervisor_type,json=hypervisorType,proto3" json:"hypervisor_type,omitempty"`
	AgentVersion     string                 `protobuf:"bytes,6,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	CapabilitiesJson string                 `protobuf:"bytes,7,opt,name=capabilities_json,json=capabilitiesJson,proto3" json:"capabilities_json,omitempty"`
	CpuCores         int32                  `protobuf:"varint,8,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuThreads       int32                  `protobuf:"varint,9,opt,name=cpu_threads,json=cpuThreads,proto3" json:"cpu_threads,omitempty"`
	MemoryBytes      int64                  `protobuf:"varint,10,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	DiskBytes        int64                  `protobuf:"varint,11,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	GpuCores         int32                  `protobuf:"varint,12,opt,name=gpu_cores,json=gpuCores,proto3" json:"gpu_cores,omitempty"`
	GpuMemoryBytes   int64                  `protobuf:"varint,13,opt,name=gpu_memory_bytes,json=gpuMemoryBytes,proto3" json:"gpu_memory_bytes,omitempty"`
	CpuModel         string                 `protobuf:"bytes,14,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	RamModel         string                 `protobuf:"bytes,15,opt,name=ram_model,json=ramModel,proto3" json:"ram_model,omitempty"`
	DiskModel        string                 `protobuf:"bytes,16,opt,name=disk_model,json=diskModel,proto3" json:"disk_model,omitempty"`
	GpuModel         string                 `protobuf:"bytes,17,opt,name=gpu_model,json=gpuModel,proto3" json:"gpu_model,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterHost) Reset() {
	*x = RegisterHost{}
	mi := &file_proto_agent_registry_v1_agent_enrollment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHost) ProtoMessage() {}

func (x *RegisterHost) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_registry_v1_agent_enrollment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHost.ProtoReflect.Descriptor instead.
func (*RegisterHost) Descriptor() ([]byte, []int) {
	return file_proto_agent_registry_v1_agent_enrollment_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterHost) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterHost) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RegisterHost) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterHost) GetPrivateIp() string {
	if x != nil {
		return x.PrivateIp
	}
	return ""
}

func (x *RegisterHost) GetHypervisorType() string {
	if x != nil {
		return x.HypervisorType
	}
	return ""
}

func (x *RegisterHost) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterHost) GetCapabilitiesJson() string {
	if x != nil {
		return x.CapabilitiesJson
	}
	return ""
}

func (x *RegisterHost) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *RegisterHost) GetCpuThreads() int32 {
	if x != nil {
		return x.CpuThreads
	}
	return 0
}

func (x *RegisterHost) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *RegisterHost) GetDiskBytes() int64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

func (x *RegisterHost) GetGpuCores() int32 {
	if x != nil {
		return x.GpuCores
	}
	return 0
}

func (x *RegisterHost) GetGpuMemoryBytes() int64 {
	if x != nil {
		return x.GpuMemoryBytes
	}
	return 0
}

func (x *RegisterHost) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *RegisterHost) GetRamModel() string {
	if x != nil {
		return x.RamModel
	}
	return ""
}

func (x *RegisterHost) GetDiskModel() string {
	if x != nil {
		return x.DiskModel
	}
	return ""
}

func (x *RegisterHost) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

type RegisterAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAck) Reset() {
	*x = RegisterAck{}
	mi := &file_proto_agent_registry_v1_agent_enrollment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAck) ProtoMessage() {}

func (x *RegisterAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_registry_v1_agent_enrollment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAck.ProtoReflect.Descriptor instead.
func (*RegisterAck) Descriptor() ([]byte, []int) {
	return file_proto_agent_registry_v1_agent_enrollment_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAck) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RegisterAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterAck) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_proto_agent_registry_v1_agent_enrollment_proto protoreflect.FileDescriptor

const file_proto_agent_registry_v1_agent_enrollment_proto_rawDesc = "" +
	"\n" +
	".proto/agent/registry/v1/agent_enrollment.proto\x12\x11agent.registry.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x01\n" +
	"\x1bBootstrapEnrollAgentRequest\x12'\n" +
	"\x0fbootstrap_token\x18\x01 \x01(\tR\x0ebootstrapToken\x12,\n" +
	"\x12requested_agent_id\x18\x02 \x01(\tR\x10requestedAgentId\x12\x17\n" +
	"\acsr_pem\x18\x03 \x01(\tR\x06csrPem\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\"\xc3\x01\n" +
	"\x1cBootstrapEnrollAgentResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12&\n" +
	"\x0fclient_cert_pem\x18\x02 \x01(\tR\rclientCertPem\x12\x1e\n" +
	"\vca_cert_pem\x18\x03 \x01(\tR\tcaCertPem\x12@\n" +
	"\x0ecert_not_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fcertNotAfter\"\xb5\x04\n" +
	"\fRegisterHost\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"private_ip\x18\x04 \x01(\tR\tprivateIp\x12'\n" +
	"\x0fhypervisor_type\x18\x05 \x01(\tR\x0ehypervisorType\x12#\n" +
	"\ragent_version\x18\x06 \x01(\tR\fagentVersion\x12+\n" +
	"\x11capabilities_json\x18\a \x01(\tR\x10capabilitiesJson\x12\x1b\n" +
	"\tcpu_cores\x18\b \x01(\x05R\bcpuCores\x12\x1f\n" +
	"\vcpu_threads\x18\t \x01(\x05R\n" +
	"cpuThreads\x12!\n" +
	"\fmemory_bytes\x18\n" +
	" \x01(\x03R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\v \x01(\x03R\tdiskBytes\x12\x1b\n" +
	"\tgpu_cores\x18\f \x01(\x05R\bgpuCores\x12(\n" +
	"\x10gpu_memory_bytes\x18\r \x01(\x03R\x0egpuMemoryBytes\x12\x1b\n" +
	"\tcpu_model\x18\x0e \x01(\tR\bcpuModel\x12\x1b\n" +
	"\tram_model\x18\x0f \x01(\tR\bramModel\x12\x1d\n" +
	"\n" +
	"disk_model\x18\x10 \x01(\tR\tdiskModel\x12\x1b\n" +
	"\tgpu_model\x18\x11 \x01(\tR\bgpuModel\"W\n" +
	"\vRegisterAck\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeIdB4Z2hypervisor/internal/transport/grpc/agentregistryv1b\x06proto3"

var (
	file_proto_agent_registry_v1_agent_enrollment_proto_rawDescOnce sync.Once
	file_proto_agent_registry_v1_agent_enrollment_proto_rawDescData []byte
)

func file_proto_agent_registry_v1_agent_enrollment_proto_rawDescGZIP() []byte {
	file_proto_agent_registry_v1_agent_enrollment_proto_rawDescOnce.Do(func() {
		file_proto_agent_registry_v1_agent_enrollment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_registry_v1_agent_enrollment_proto_rawDesc), len(file_proto_agent_registry_v1_agent_enrollment_proto_rawDesc)))
	})
	return file_proto_agent_registry_v1_agent_enrollment_proto_rawDescData
}

var file_proto_agent_registry_v1_agent_enrollment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_agent_registry_v1_agent_enrollment_proto_goTypes = []any{
	(*BootstrapEnrollAgentRequest)(nil),  // 0: agent.registry.v1.BootstrapEnrollAgentRequest
	(*BootstrapEnrollAgentResponse)(nil), // 1: agent.registry.v1.BootstrapEnrollAgentResponse
	(*RegisterHost)(nil),                 // 2: agent.registry.v1.RegisterHost
	(*RegisterAck)(nil),                  // 3: agent.registry.v1.RegisterAck
	(*timestamppb.Timestamp)(nil),        // 4: google.protobuf.Timestamp
}
var file_proto_agent_registry_v1_agent_enrollment_proto_depIdxs = []int32{
	4, // 0: agent.registry.v1.BootstrapEnrollAgentResponse.cert_not_after:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_agent_registry_v1_agent_enrollment_proto_init() }
func file_proto_agent_registry_v1_agent_enrollment_proto_init() {
	if File_proto_agent_registry_v1_agent_enrollment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_registry_v1_agent_enrollment_proto_rawDesc), len(file_proto_agent_registry_v1_agent_enrollment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_agent_registry_v1_agent_enrollment_proto_goTypes,
		DependencyIndexes: file_proto_agent_registry_v1_agent_enrollment_proto_depIdxs,
		MessageInfos:      file_proto_agent_registry_v1_agent_enrollment_proto_msgTypes,
	}.Build()
	File_proto_agent_registry_v1_agent_enrollment_proto = out.File
	file_proto_agent_registry_v1_agent_enrollment_proto_goTypes = nil
	file_proto_agent_registry_v1_agent_enrollment_proto_depIdxs = nil
}
