// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/agent/registry/v1/agent_registry.proto

package agentregistryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentToHypervisor struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StreamId string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Seq      uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*AgentToHypervisor_RegisterHost
	//	*AgentToHypervisor_Heartbeat
	//	*AgentToHypervisor_HostInventory
	//	*AgentToHypervisor_NodeMetric
	//	*AgentToHypervisor_VpsMetric
	//	*AgentToHypervisor_CommandResult
	Message       isAgentToHypervisor_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToHypervisor) Reset() {
	*x = AgentToHypervisor{}
	mi := &file_proto_agent_registry_v1_agent_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToHypervisor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToHypervisor) ProtoMessage() {}

func (x *AgentToHypervisor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_registry_v1_agent_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToHypervisor.ProtoReflect.Descriptor instead.
func (*AgentToHypervisor) Descriptor() ([]byte, []int) {
	return file_proto_agent_registry_v1_agent_registry_proto_rawDescGZIP(), []int{0}
}

func (x *AgentToHypervisor) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *AgentToHypervisor) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AgentToHypervisor) GetMessage() isAgentToHypervisor_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AgentToHypervisor) GetRegisterHost() *RegisterHost {
	if x != nil {
		if x, ok := x.Message.(*AgentToHypervisor_RegisterHost); ok {
			return x.RegisterHost
		}
	}
	return nil
}

func (x *AgentToHypervisor) GetHeartbeat() *AgentHeartbeat {
	if x != nil {
		if x, ok := x.Message.(*AgentToHypervisor_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentToHypervisor) GetHostInventory() *HostInventory {
	if x != nil {
		if x, ok := x.Message.(*AgentToHypervisor_HostInventory); ok {
			return x.HostInventory
		}
	}
	return nil
}

func (x *AgentToHypervisor) GetNodeMetric() *NodeMetricSample {
	if x != nil {
		if x, ok := x.Message.(*AgentToHypervisor_NodeMetric); ok {
			return x.NodeMetric
		}
	}
	return nil
}

func (x *AgentToHypervisor) GetVpsMetric() *VPSMetricSample {
	if x != nil {
		if x, ok := x.Message.(*AgentToHypervisor_VpsMetric); ok {
			return x.VpsMetric
		}
	}
	return nil
}

func (x *AgentToHypervisor) GetCommandResult() *AgentCommandResult {
	if x != nil {
		if x, ok := x.Message.(*AgentToHypervisor_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

type isAgentToHypervisor_Message interface {
	isAgentToHypervisor_Message()
}

type AgentToHypervisor_RegisterHost struct {
	RegisterHost *RegisterHost `protobuf:"bytes,3,opt,name=register_host,json=registerHost,proto3,oneof"`
}

type AgentToHypervisor_Heartbeat struct {
	Heartbeat *AgentHeartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type AgentToHypervisor_HostInventory struct {
	HostInventory *HostInventory `protobuf:"bytes,5,opt,name=host_inventory,json=hostInventory,proto3,oneof"`
}

type AgentToHypervisor_NodeMetric struct {
	NodeMetric *NodeMetricSample `protobuf:"bytes,6,opt,name=node_metric,json=nodeMetric,proto3,oneof"`
}

type AgentToHypervisor_VpsMetric struct {
	VpsMetric *VPSMetricSample `protobuf:"bytes,7,opt,name=vps_metric,json=vpsMetric,proto3,oneof"`
}

type AgentToHypervisor_CommandResult struct {
	CommandResult *AgentCommandResult `protobuf:"bytes,8,opt,name=command_result,json=commandResult,proto3,oneof"`
}

func (*AgentToHypervisor_RegisterHost) isAgentToHypervisor_Message() {}

func (*AgentToHypervisor_Heartbeat) isAgentToHypervisor_Message() {}

func (*AgentToHypervisor_HostInventory) isAgentToHypervisor_Message() {}

func (*AgentToHypervisor_NodeMetric) isAgentToHypervisor_Message() {}

func (*AgentToHypervisor_VpsMetric) isAgentToHypervisor_Message() {}

func (*AgentToHypervisor_CommandResult) isAgentToHypervisor_Message() {}

type HypervisorToAgent struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StreamId string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Seq      uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*HypervisorToAgent_RegisterAck
	//	*HypervisorToAgent_HeartbeatAck
	//	*HypervisorToAgent_Command
	Message       isHypervisorToAgent_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HypervisorToAgent) Reset() {
	*x = HypervisorToAgent{}
	mi := &file_proto_agent_registry_v1_agent_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HypervisorToAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HypervisorToAgent) ProtoMessage() {}

func (x *HypervisorToAgent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_registry_v1_agent_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HypervisorToAgent.ProtoReflect.Descriptor instead.
func (*HypervisorToAgent) Descriptor() ([]byte, []int) {
	return file_proto_agent_registry_v1_agent_registry_proto_rawDescGZIP(), []int{1}
}

func (x *HypervisorToAgent) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *HypervisorToAgent) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *HypervisorToAgent) GetMessage() isHypervisorToAgent_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *HypervisorToAgent) GetRegisterAck() *RegisterAck {
	if x != nil {
		if x, ok := x.Message.(*HypervisorToAgent_RegisterAck); ok {
			return x.RegisterAck
		}
	}
	return nil
}

func (x *HypervisorToAgent) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Message.(*HypervisorToAgent_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *HypervisorToAgent) GetCommand() *AgentCommand {
	if x != nil {
		if x, ok := x.Message.(*HypervisorToAgent_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isHypervisorToAgent_Message interface {
	isHypervisorToAgent_Message()
}

type HypervisorToAgent_RegisterAck struct {
	RegisterAck *RegisterAck `protobuf:"bytes,3,opt,name=register_ack,json=registerAck,proto3,oneof"`
}

type HypervisorToAgent_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,4,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type HypervisorToAgent_Command struct {
	Command *AgentCommand `protobuf:"bytes,5,opt,name=command,proto3,oneof"`
}

func (*HypervisorToAgent_RegisterAck) isHypervisorToAgent_Message() {}

func (*HypervisorToAgent_HeartbeatAck) isHypervisorToAgent_Message() {}

func (*HypervisorToAgent_Command) isHypervisorToAgent_Message() {}

var File_proto_agent_registry_v1_agent_registry_proto protoreflect.FileDescriptor

const file_proto_agent_registry_v1_agent_registry_proto_rawDesc = "" +
	"\n" +
	",proto/agent/registry/v1/agent_registry.proto\x12\x11agent.registry.v1\x1a*proto/agent/registry/v1/agent_common.proto\x1a.proto/agent/registry/v1/agent_enrollment.proto\x1a-proto/agent/registry/v1/agent_telemetry.proto\"\x80\x04\n" +
	"\x11AgentToHypervisor\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12F\n" +
	"\rregister_host\x18\x03 \x01(\v2\x1f.agent.registry.v1.RegisterHostH\x00R\fregisterHost\x12A\n" +
	"\theartbeat\x18\x04 \x01(\v2!.agent.registry.v1.AgentHeartbeatH\x00R\theartbeat\x12I\n" +
	"\x0ehost_inventory\x18\x05 \x01(\v2 .agent.registry.v1.HostInventoryH\x00R\rhostInventory\x12F\n" +
	"\vnode_metric\x18\x06 \x01(\v2#.agent.registry.v1.NodeMetricSampleH\x00R\n" +
	"nodeMetric\x12C\n" +
	"\n" +
	"vps_metric\x18\a \x01(\v2\".agent.registry.v1.VPSMetricSampleH\x00R\tvpsMetric\x12N\n" +
	"\x0ecommand_result\x18\b \x01(\v2%.agent.registry.v1.AgentCommandResultH\x00R\rcommandResultB\t\n" +
	"\amessage\"\x97\x02\n" +
	"\x11HypervisorToAgent\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12C\n" +
	"\fregister_ack\x18\x03 \x01(\v2\x1e.agent.registry.v1.RegisterAckH\x00R\vregisterAck\x12F\n" +
	"\rheartbeat_ack\x18\x04 \x01(\v2\x1f.agent.registry.v1.HeartbeatAckH\x00R\fheartbeatAck\x12;\n" +
	"\acommand\x18\x05 \x01(\v2\x1f.agent.registry.v1.AgentCommandH\x00R\acommandB\t\n" +
	"\amessage2\xee\x01\n" +
	"\rAgentRegistry\x12d\n" +
	"\x12AgentControlStream\x12$.agent.registry.v1.AgentToHypervisor\x1a$.agent.registry.v1.HypervisorToAgent(\x010\x01\x12w\n" +
	"\x14BootstrapEnrollAgent\x12..agent.registry.v1.BootstrapEnrollAgentRequest\x1a/.agent.registry.v1.BootstrapEnrollAgentResponseB4Z2hypervisor/internal/transport/grpc/agentregistryv1b\x06proto3"

var (
	file_proto_agent_registry_v1_agent_registry_proto_rawDescOnce sync.Once
	file_proto_agent_registry_v1_agent_registry_proto_rawDescData []byte
)

func file_proto_agent_registry_v1_agent_registry_proto_rawDescGZIP() []byte {
	file_proto_agent_registry_v1_agent_registry_proto_rawDescOnce.Do(func() {
		file_proto_agent_registry_v1_agent_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_registry_v1_agent_registry_proto_rawDesc), len(file_proto_agent_registry_v1_agent_registry_proto_rawDesc)))
	})
	return file_proto_agent_registry_v1_agent_registry_proto_rawDescData
}

var file_proto_agent_registry_v1_agent_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_agent_registry_v1_agent_registry_proto_goTypes = []any{
	(*AgentToHypervisor)(nil),            // 0: agent.registry.v1.AgentToHypervisor
	(*HypervisorToAgent)(nil),            // 1: agent.registry.v1.HypervisorToAgent
	(*RegisterHost)(nil),                 // 2: agent.registry.v1.RegisterHost
	(*AgentHeartbeat)(nil),               // 3: agent.registry.v1.AgentHeartbeat
	(*HostInventory)(nil),                // 4: agent.registry.v1.HostInventory
	(*NodeMetricSample)(nil),             // 5: agent.registry.v1.NodeMetricSample
	(*VPSMetricSample)(nil),              // 6: agent.registry.v1.VPSMetricSample
	(*AgentCommandResult)(nil),           // 7: agent.registry.v1.AgentCommandResult
	(*RegisterAck)(nil),                  // 8: agent.registry.v1.RegisterAck
	(*HeartbeatAck)(nil),                 // 9: agent.registry.v1.HeartbeatAck
	(*AgentCommand)(nil),                 // 10: agent.registry.v1.AgentCommand
	(*BootstrapEnrollAgentRequest)(nil),  // 11: agent.registry.v1.BootstrapEnrollAgentRequest
	(*BootstrapEnrollAgentResponse)(nil), // 12: agent.registry.v1.BootstrapEnrollAgentResponse
}
var file_proto_agent_registry_v1_agent_registry_proto_depIdxs = []int32{
	2,  // 0: agent.registry.v1.AgentToHypervisor.register_host:type_name -> agent.registry.v1.RegisterHost
	3,  // 1: agent.registry.v1.AgentToHypervisor.heartbeat:type_name -> agent.registry.v1.AgentHeartbeat
	4,  // 2: agent.registry.v1.AgentToHypervisor.host_inventory:type_name -> agent.registry.v1.HostInventory
	5,  // 3: agent.registry.v1.AgentToHypervisor.node_metric:type_name -> agent.registry.v1.NodeMetricSample
	6,  // 4: agent.registry.v1.AgentToHypervisor.vps_metric:type_name -> agent.registry.v1.VPSMetricSample
	7,  // 5: agent.registry.v1.AgentToHypervisor.command_result:type_name -> agent.registry.v1.AgentCommandResult
	8,  // 6: agent.registry.v1.HypervisorToAgent.register_ack:type_name -> agent.registry.v1.RegisterAck
	9,  // 7: agent.registry.v1.HypervisorToAgent.heartbeat_ack:type_name -> agent.registry.v1.HeartbeatAck
	10, // 8: agent.registry.v1.HypervisorToAgent.command:type_name -> agent.registry.v1.AgentCommand
	0,  // 9: agent.registry.v1.AgentRegistry.AgentControlStream:input_type -> agent.registry.v1.AgentToHypervisor
	11, // 10: agent.registry.v1.AgentRegistry.BootstrapEnrollAgent:input_type -> agent.registry.v1.BootstrapEnrollAgentRequest
	1,  // 11: agent.registry.v1.AgentRegistry.AgentControlStream:output_type -> agent.registry.v1.HypervisorToAgent
	12, // 12: agent.registry.v1.AgentRegistry.BootstrapEnrollAgent:output_type -> agent.registry.v1.BootstrapEnrollAgentResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_agent_registry_v1_agent_registry_proto_init() }
func file_proto_agent_registry_v1_agent_registry_proto_init() {
	if File_proto_agent_registry_v1_agent_registry_proto != nil {
		return
	}
	file_proto_agent_registry_v1_agent_common_proto_init()
	file_proto_agent_registry_v1_agent_enrollment_proto_init()
	file_proto_agent_registry_v1_agent_telemetry_proto_init()
	file_proto_agent_registry_v1_agent_registry_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentToHypervisor_RegisterHost)(nil),
		(*AgentToHypervisor_Heartbeat)(nil),
		(*AgentToHypervisor_HostInventory)(nil),
		(*AgentToHypervisor_NodeMetric)(nil),
		(*AgentToHypervisor_VpsMetric)(nil),
		(*AgentToHypervisor_CommandResult)(nil),
	}
	file_proto_agent_registry_v1_agent_registry_proto_msgTypes[1].OneofWrappers = []any{
		(*HypervisorToAgent_RegisterAck)(nil),
		(*HypervisorToAgent_HeartbeatAck)(nil),
		(*HypervisorToAgent_Command)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_registry_v1_agent_registry_proto_rawDesc), len(file_proto_agent_registry_v1_agent_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_registry_v1_agent_registry_proto_goTypes,
		DependencyIndexes: file_proto_agent_registry_v1_agent_registry_proto_depIdxs,
		MessageInfos:      file_proto_agent_registry_v1_agent_registry_proto_msgTypes,
	}.Build()
	File_proto_agent_registry_v1_agent_registry_proto = out.File
	file_proto_agent_registry_v1_agent_registry_proto_goTypes = nil
	file_proto_agent_registry_v1_agent_registry_proto_depIdxs = nil
}
