// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/agent/registry/v1/agent_telemetry.proto

package agentregistryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoragePoolInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	UsedBytes     int64                  `protobuf:"varint,5,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,7,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoragePoolInventory) Reset() {
	*x = StoragePoolInventory{}
	mi := &file_proto_agent_registry_v1_agent_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoragePoolInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoragePoolInventory) ProtoMessage() {}

func (x *StoragePoolInventory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_registry_v1_agent_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoragePoolInventory.ProtoReflect.Descriptor instead.
func (*StoragePoolInventory) Descriptor() ([]byte, []int) {
	return file_proto_agent_registry_v1_agent_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *StoragePoolInventory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoragePoolInventory) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *StoragePoolInventory) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StoragePoolInventory) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *StoragePoolInventory) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *StoragePoolInventory) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StoragePoolInventory) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type NetworkInterfaceInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MacAddress    string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Ipv4Address   string                 `protobuf:"bytes,3,opt,name=ipv4_address,json=ipv4Address,proto3" json:"ipv4_address,omitempty"`
	Ipv6Address   string                 `protobuf:"bytes,4,opt,name=ipv6_address,json=ipv6Address,proto3" json:"ipv6_address,omitempty"`
	SpeedMbps     int32                  `protobuf:"varint,5,opt,name=speed_mbps,json=speedMbps,proto3" json:"speed_mbps,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	MetadataJson  string                 `protobuf:"bytes,7,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterfaceInventory) Reset() {
	*x = NetworkInterfaceInventory{}
	mi := &file_proto_agent_registry_v1_agent_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterfaceInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterfaceInventory) ProtoMessage() {}

func (x *NetworkInterfaceInventory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_registry_v1_agent_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterfaceInventory.ProtoReflect.Descriptor instead.
func (*NetworkInterfaceInventory) Descriptor() ([]byte, []int) {
	return file_proto_agent_registry_v1_agent_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkInterfaceInventory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterfaceInventory) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkInterfaceInventory) GetIpv4Address() string {
	if x != nil {
		return x.Ipv4Address
	}
	return ""
}

func (x *NetworkInterfaceInventory) GetIpv6Address() string {
	if x != nil {
		return x.Ipv6Address
	}
	return ""
}

func (x *NetworkInterfaceInventory) GetSpeedMbps() int32 {
	if x != nil {
		return x.SpeedMbps
	}
	return 0
}

func (x *NetworkInterfaceInventory) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NetworkInterfaceInventory) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type HostInventory struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	AgentId           string                       `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId            string                       `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	StoragePools      []*StoragePoolInventory      `protobuf:"bytes,3,rep,name=storage_pools,json=storagePools,proto3" json:"storage_pools,omitempty"`
	NetworkInterfaces []*NetworkInterfaceInventory `protobuf:"bytes,4,rep,name=network_interfaces,json=networkInterfaces,proto3" json:"network_interfaces,omitempty"`
	CollectedAt       *timestamppb.Timestamp       `protobuf:"bytes,5,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostInventory) Reset() {
	*x = HostInventory{}
	mi := &file_proto_agent_registry_v1_agent_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInventory) ProtoMessage() {}

func (x *HostInventory) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_registry_v1_agent_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInventory.ProtoReflect.Descriptor instead.
func (*HostInventory) Descriptor() ([]byte, []int) {
	return file_proto_agent_registry_v1_agent_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *HostInventory) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HostInventory) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HostInventory) GetStoragePools() []*StoragePoolInventory {
	if x != nil {
		return x.StoragePools
	}
	return nil
}

func (x *HostInventory) GetNetworkInterfaces() []*NetworkInterfaceInventory {
	if x != nil {
		return x.NetworkInterfaces
	}
	return nil
}

func (x *HostInventory) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

type NodeMetricSample struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId         string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	CpuUsedPercent float64                `protobuf:"fixed64,3,opt,name=cpu_used_percent,json=cpuUsedPercent,proto3" json:"cpu_used_percent,omitempty"`
	CpuUsedCores   float64                `protobuf:"fixed64,4,opt,name=cpu_used_cores,json=cpuUsedCores,proto3" json:"cpu_used_cores,omitempty"`
	RamUsedGib     float64                `protobuf:"fixed64,5,opt,name=ram_used_gib,json=ramUsedGib,proto3" json:"ram_used_gib,omitempty"`
	RamUsedPercent float64                `protobuf:"fixed64,6,opt,name=ram_used_percent,json=ramUsedPercent,proto3" json:"ram_used_percent,omitempty"`
	SsdUsedGib     float64                `protobuf:"fixed64,7,opt,name=ssd_used_gib,json=ssdUsedGib,proto3" json:"ssd_used_gib,omitempty"`
	SsdUsedPercent float64                `protobuf:"fixed64,8,opt,name=ssd_used_percent,json=ssdUsedPercent,proto3" json:"ssd_used_percent,omitempty"`
	GpuUsedPercent float64                `protobuf:"fixed64,9,opt,name=gpu_used_percent,json=gpuUsedPercent,proto3" json:"gpu_used_percent,omitempty"`
	GpuUsedGib     float64                `protobuf:"fixed64,10,opt,name=gpu_used_gib,json=gpuUsedGib,proto3" json:"gpu_used_gib,omitempty"`
	NetworkRxBps   int64                  `protobuf:"varint,11,opt,name=network_rx_bps,json=networkRxBps,proto3" json:"network_rx_bps,omitempty"`
	NetworkTxBps   int64                  `protobuf:"varint,12,opt,name=network_tx_bps,json=networkTxBps,proto3" json:"network_tx_bps,omitempty"`
	DiskReadBps    uint64                 `protobuf:"varint,13,opt,name=disk_read_bps,json=diskReadBps,proto3" json:"disk_read_bps,omitempty"`
	DiskWriteBps   uint64                 `protobuf:"varint,14,opt,name=disk_write_bps,json=diskWriteBps,proto3" json:"disk_write_bps,omitempty"`
	SampledAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=sampled_at,json=sampledAt,proto3" json:"sampled_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeMetricSample) Reset() {
	*x = NodeMetricSample{}
	mi := &file_proto_agent_registry_v1_agent_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetricSample) ProtoMessage() {}

func (x *NodeMetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_registry_v1_agent_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetricSample.ProtoReflect.Descriptor instead.
func (*NodeMetricSample) Descriptor() ([]byte, []int) {
	return file_proto_agent_registry_v1_agent_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *NodeMetricSample) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *NodeMetricSample) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *NodeMetricSample) GetCpuUsedPercent() float64 {
	if x != nil {
		return x.CpuUsedPercent
	}
	return 0
}

func (x *NodeMetricSample) GetCpuUsedCores() float64 {
	if x != nil {
		return x.CpuUsedCores
	}
	return 0
}

func (x *NodeMetricSample) GetRamUsedGib() float64 {
	if x != nil {
		return x.RamUsedGib
	}
	return 0
}

func (x *NodeMetricSample) GetRamUsedPercent() float64 {
	if x != nil {
		return x.RamUsedPercent
	}
	return 0
}

func (x *NodeMetricSample) GetSsdUsedGib() float64 {
	if x != nil {
		return x.SsdUsedGib
	}
	return 0
}

func (x *NodeMetricSample) GetSsdUsedPercent() float64 {
	if x != nil {
		return x.SsdUsedPercent
	}
	return 0
}

func (x *NodeMetricSample) GetGpuUsedPercent() float64 {
	if x != nil {
		return x.GpuUsedPercent
	}
	return 0
}

func (x *NodeMetricSample) GetGpuUsedGib() float64 {
	if x != nil {
		return x.GpuUsedGib
	}
	return 0
}

func (x *NodeMetricSample) GetNetworkRxBps() int64 {
	if x != nil {
		return x.NetworkRxBps
	}
	return 0
}

func (x *NodeMetricSample) GetNetworkTxBps() int64 {
	if x != nil {
		return x.NetworkTxBps
	}
	return 0
}

func (x *NodeMetricSample) GetDiskReadBps() uint64 {
	if x != nil {
		return x.DiskReadBps
	}
	return 0
}

func (x *NodeMetricSample) GetDiskWriteBps() uint64 {
	if x != nil {
		return x.DiskWriteBps
	}
	return 0
}

func (x *NodeMetricSample) GetSampledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SampledAt
	}
	return nil
}

type VPSMetricSample struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	HostId         string                 `protobuf:"bytes,2,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	VpsId          string                 `protobuf:"bytes,3,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	CpuUsedPercent float64                `protobuf:"fixed64,4,opt,name=cpu_used_percent,json=cpuUsedPercent,proto3" json:"cpu_used_percent,omitempty"`
	CpuUsedCores   float64                `protobuf:"fixed64,5,opt,name=cpu_used_cores,json=cpuUsedCores,proto3" json:"cpu_used_cores,omitempty"`
	RamUsedGib     float64                `protobuf:"fixed64,6,opt,name=ram_used_gib,json=ramUsedGib,proto3" json:"ram_used_gib,omitempty"`
	RamUsedPercent float64                `protobuf:"fixed64,7,opt,name=ram_used_percent,json=ramUsedPercent,proto3" json:"ram_used_percent,omitempty"`
	SsdUsedGib     float64                `protobuf:"fixed64,8,opt,name=ssd_used_gib,json=ssdUsedGib,proto3" json:"ssd_used_gib,omitempty"`
	SsdUsedPercent float64                `protobuf:"fixed64,9,opt,name=ssd_used_percent,json=ssdUsedPercent,proto3" json:"ssd_used_percent,omitempty"`
	GpuUsedPercent float64                `protobuf:"fixed64,10,opt,name=gpu_used_percent,json=gpuUsedPercent,proto3" json:"gpu_used_percent,omitempty"`
	GpuUsedGib     float64                `protobuf:"fixed64,11,opt,name=gpu_used_gib,json=gpuUsedGib,proto3" json:"gpu_used_gib,omitempty"`
	NetworkRxBps   int64                  `protobuf:"varint,12,opt,name=network_rx_bps,json=networkRxBps,proto3" json:"network_rx_bps,omitempty"`
	NetworkTxBps   int64                  `protobuf:"varint,13,opt,name=network_tx_bps,json=networkTxBps,proto3" json:"network_tx_bps,omitempty"`
	DiskReadBps    uint64                 `protobuf:"varint,14,opt,name=disk_read_bps,json=diskReadBps,proto3" json:"disk_read_bps,omitempty"`
	DiskWriteBps   uint64                 `protobuf:"varint,15,opt,name=disk_write_bps,json=diskWriteBps,proto3" json:"disk_write_bps,omitempty"`
	DiskIopsRead   float64                `protobuf:"fixed64,16,opt,name=disk_iops_read,json=diskIopsRead,proto3" json:"disk_iops_read,omitempty"`
	DiskIopsWrite  float64                `protobuf:"fixed64,17,opt,name=disk_iops_write,json=diskIopsWrite,proto3" json:"disk_iops_write,omitempty"`
	SampledAt      *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=sampled_at,json=sampledAt,proto3" json:"sampled_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VPSMetricSample) Reset() {
	*x = VPSMetricSample{}
	mi := &file_proto_agent_registry_v1_agent_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPSMetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPSMetricSample) ProtoMessage() {}

func (x *VPSMetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_registry_v1_agent_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPSMetricSample.ProtoReflect.Descriptor instead.
func (*VPSMetricSample) Descriptor() ([]byte, []int) {
	return file_proto_agent_registry_v1_agent_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *VPSMetricSample) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *VPSMetricSample) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *VPSMetricSample) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *VPSMetricSample) GetCpuUsedPercent() float64 {
	if x != nil {
		return x.CpuUsedPercent
	}
	return 0
}

func (x *VPSMetricSample) GetCpuUsedCores() float64 {
	if x != nil {
		return x.CpuUsedCores
	}
	return 0
}

func (x *VPSMetricSample) GetRamUsedGib() float64 {
	if x != nil {
		return x.RamUsedGib
	}
	return 0
}

func (x *VPSMetricSample) GetRamUsedPercent() float64 {
	if x != nil {
		return x.RamUsedPercent
	}
	return 0
}

func (x *VPSMetricSample) GetSsdUsedGib() float64 {
	if x != nil {
		return x.SsdUsedGib
	}
	return 0
}

func (x *VPSMetricSample) GetSsdUsedPercent() float64 {
	if x != nil {
		return x.SsdUsedPercent
	}
	return 0
}

func (x *VPSMetricSample) GetGpuUsedPercent() float64 {
	if x != nil {
		return x.GpuUsedPercent
	}
	return 0
}

func (x *VPSMetricSample) GetGpuUsedGib() float64 {
	if x != nil {
		return x.GpuUsedGib
	}
	return 0
}

func (x *VPSMetricSample) GetNetworkRxBps() int64 {
	if x != nil {
		return x.NetworkRxBps
	}
	return 0
}

func (x *VPSMetricSample) GetNetworkTxBps() int64 {
	if x != nil {
		return x.NetworkTxBps
	}
	return 0
}

func (x *VPSMetricSample) GetDiskReadBps() uint64 {
	if x != nil {
		return x.DiskReadBps
	}
	return 0
}

func (x *VPSMetricSample) GetDiskWriteBps() uint64 {
	if x != nil {
		return x.DiskWriteBps
	}
	return 0
}

func (x *VPSMetricSample) GetDiskIopsRead() float64 {
	if x != nil {
		return x.DiskIopsRead
	}
	return 0
}

func (x *VPSMetricSample) GetDiskIopsWrite() float64 {
	if x != nil {
		return x.DiskIopsWrite
	}
	return 0
}

func (x *VPSMetricSample) GetSampledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SampledAt
	}
	return nil
}

var File_proto_agent_registry_v1_agent_telemetry_proto protoreflect.FileDescriptor

const file_proto_agent_registry_v1_agent_telemetry_proto_rawDesc = "" +
	"\n" +
	"-proto/agent/registry/v1/agent_telemetry.proto\x12\x11agent.registry.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x01\n" +
	"\x14StoragePoolInventory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x05 \x01(\x03R\tusedBytes\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12#\n" +
	"\rmetadata_json\x18\a \x01(\tR\fmetadataJson\"\xf2\x01\n" +
	"\x19NetworkInterfaceInventory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12!\n" +
	"\fipv4_address\x18\x03 \x01(\tR\vipv4Address\x12!\n" +
	"\fipv6_address\x18\x04 \x01(\tR\vipv6Address\x12\x1d\n" +
	"\n" +
	"speed_mbps\x18\x05 \x01(\x05R\tspeedMbps\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12#\n" +
	"\rmetadata_json\x18\a \x01(\tR\fmetadataJson\"\xad\x02\n" +
	"\rHostInventory\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12L\n" +
	"\rstorage_pools\x18\x03 \x03(\v2'.agent.registry.v1.StoragePoolInventoryR\fstoragePools\x12[\n" +
	"\x12network_interfaces\x18\x04 \x03(\v2,.agent.registry.v1.NetworkInterfaceInventoryR\x11networkInterfaces\x12=\n" +
	"\fcollected_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\"\xcb\x04\n" +
	"\x10NodeMetricSample\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12(\n" +
	"\x10cpu_used_percent\x18\x03 \x01(\x01R\x0ecpuUsedPercent\x12$\n" +
	"\x0ecpu_used_cores\x18\x04 \x01(\x01R\fcpuUsedCores\x12 \n" +
	"\fram_used_gib\x18\x05 \x01(\x01R\n" +
	"ramUsedGib\x12(\n" +
	"\x10ram_used_percent\x18\x06 \x01(\x01R\x0eramUsedPercent\x12 \n" +
	"\fssd_used_gib\x18\a \x01(\x01R\n" +
	"ssdUsedGib\x12(\n" +
	"\x10ssd_used_percent\x18\b \x01(\x01R\x0essdUsedPercent\x12(\n" +
	"\x10gpu_used_percent\x18\t \x01(\x01R\x0egpuUsedPercent\x12 \n" +
	"\fgpu_used_gib\x18\n" +
	" \x01(\x01R\n" +
	"gpuUsedGib\x12$\n" +
	"\x0enetwork_rx_bps\x18\v \x01(\x03R\fnetworkRxBps\x12$\n" +
	"\x0enetwork_tx_bps\x18\f \x01(\x03R\fnetworkTxBps\x12\"\n" +
	"\rdisk_read_bps\x18\r \x01(\x04R\vdiskReadBps\x12$\n" +
	"\x0edisk_write_bps\x18\x0e \x01(\x04R\fdiskWriteBps\x129\n" +
	"\n" +
	"sampled_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tsampledAt\"\xaf\x05\n" +
	"\x0fVPSMetricSample\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\ahost_id\x18\x02 \x01(\tR\x06hostId\x12\x15\n" +
	"\x06vps_id\x18\x03 \x01(\tR\x05vpsId\x12(\n" +
	"\x10cpu_used_percent\x18\x04 \x01(\x01R\x0ecpuUsedPercent\x12$\n" +
	"\x0ecpu_used_cores\x18\x05 \x01(\x01R\fcpuUsedCores\x12 \n" +
	"\fram_used_gib\x18\x06 \x01(\x01R\n" +
	"ramUsedGib\x12(\n" +
	"\x10ram_used_percent\x18\a \x01(\x01R\x0eramUsedPercent\x12 \n" +
	"\fssd_used_gib\x18\b \x01(\x01R\n" +
	"ssdUsedGib\x12(\n" +
	"\x10ssd_used_percent\x18\t \x01(\x01R\x0essdUsedPercent\x12(\n" +
	"\x10gpu_used_percent\x18\n" +
	" \x01(\x01R\x0egpuUsedPercent\x12 \n" +
	"\fgpu_used_gib\x18\v \x01(\x01R\n" +
	"gpuUsedGib\x12$\n" +
	"\x0enetwork_rx_bps\x18\f \x01(\x03R\fnetworkRxBps\x12$\n" +
	"\x0enetwork_tx_bps\x18\r \x01(\x03R\fnetworkTxBps\x12\"\n" +
	"\rdisk_read_bps\x18\x0e \x01(\x04R\vdiskReadBps\x12$\n" +
	"\x0edisk_write_bps\x18\x0f \x01(\x04R\fdiskWriteBps\x12$\n" +
	"\x0edisk_iops_read\x18\x10 \x01(\x01R\fdiskIopsRead\x12&\n" +
	"\x0fdisk_iops_write\x18\x11 \x01(\x01R\rdiskIopsWrite\x129\n" +
	"\n" +
	"sampled_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tsampledAtB4Z2hypervisor/internal/transport/grpc/agentregistryv1b\x06proto3"

var (
	file_proto_agent_registry_v1_agent_telemetry_proto_rawDescOnce sync.Once
	file_proto_agent_registry_v1_agent_telemetry_proto_rawDescData []byte
)

func file_proto_agent_registry_v1_agent_telemetry_proto_rawDescGZIP() []byte {
	file_proto_agent_registry_v1_agent_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_agent_registry_v1_agent_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_registry_v1_agent_telemetry_proto_rawDesc), len(file_proto_agent_registry_v1_agent_telemetry_proto_rawDesc)))
	})
	return file_proto_agent_registry_v1_agent_telemetry_proto_rawDescData
}

var file_proto_agent_registry_v1_agent_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_agent_registry_v1_agent_telemetry_proto_goTypes = []any{
	(*StoragePoolInventory)(nil),      // 0: agent.registry.v1.StoragePoolInventory
	(*NetworkInterfaceInventory)(nil), // 1: agent.registry.v1.NetworkInterfaceInventory
	(*HostInventory)(nil),             // 2: agent.registry.v1.HostInventory
	(*NodeMetricSample)(nil),          // 3: agent.registry.v1.NodeMetricSample
	(*VPSMetricSample)(nil),           // 4: agent.registry.v1.VPSMetricSample
	(*timestamppb.Timestamp)(nil),     // 5: google.protobuf.Timestamp
}
var file_proto_agent_registry_v1_agent_telemetry_proto_depIdxs = []int32{
	0, // 0: agent.registry.v1.HostInventory.storage_pools:type_name -> agent.registry.v1.StoragePoolInventory
	1, // 1: agent.registry.v1.HostInventory.network_interfaces:type_name -> agent.registry.v1.NetworkInterfaceInventory
	5, // 2: agent.registry.v1.HostInventory.collected_at:type_name -> google.protobuf.Timestamp
	5, // 3: agent.registry.v1.NodeMetricSample.sampled_at:type_name -> google.protobuf.Timestamp
	5, // 4: agent.registry.v1.VPSMetricSample.sampled_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_agent_registry_v1_agent_telemetry_proto_init() }
func file_proto_agent_registry_v1_agent_telemetry_proto_init() {
	if File_proto_agent_registry_v1_agent_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_registry_v1_agent_telemetry_proto_rawDesc), len(file_proto_agent_registry_v1_agent_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_agent_registry_v1_agent_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_agent_registry_v1_agent_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_agent_registry_v1_agent_telemetry_proto_msgTypes,
	}.Build()
	File_proto_agent_registry_v1_agent_telemetry_proto = out.File
	file_proto_agent_registry_v1_agent_telemetry_proto_goTypes = nil
	file_proto_agent_registry_v1_agent_telemetry_proto_depIdxs = nil
}
